# Sample workflow for building and deploying a Next.js site to GitHub Pages
name: Deploy Next.js site to Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Setup Node.js
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      # ✅ Setup pnpm properly
      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8
          run_install: false

      # Cache dependencies
      - name: Restore cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.pnpm-store
            .next/cache
          key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}-${{ hashFiles('**.[jt]s', '**.[jt]sx') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-

      # ✅ Add a step to verify the lockfile presence
      - name: Verify lockfile presence
        run: |
          ls -la ${{ github.workspace }}
          if [ ! -f "pnpm-lock.yaml" ]; then
            echo "pnpm-lock.yaml not found!"
            exit 1
          fi

      # Install dependencies with --no-frozen-lockfile
      - name: Install dependencies
        run: pnpm install --no-frozen-lockfile

      # ✅ Build and export using Next.js static export
      - name: Build with Next.js
        run: pnpm next build

      # ✅ No need for `next export` step as it is handled by the config
      # Exported static files will be in the `out` folder by default
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./out

  # Deployment job
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
